-- livesql

CREATE TABLE WorkDone(
    PID VARCHAR(255),
    STEP INT,
    STATUS CHAR(10)
);

-- Populating the table

INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P100', 0, 'C');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P100', 1, 'W');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P100', 2, 'W');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P201', 0, 'C');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P201', 1, 'C');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P333', 0, 'W');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P333', 1, 'W');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P333', 2, 'W');
INSERT INTO WorkDone (PID, STEP, STATUS) VALUES ('P333', 3, 'W');

select * from WorkDone;

-- ANS

SELECT PID FROM WorkDone WHERE Status = 'C' GROUP BY PID HAVING COUNT(PID) = 1;